name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - name: Instalar o Python
        uses: actions/setup-python@v5   # acao do github para configurar o python
        with: 
          python-version: '3.12'